### ISSUE TITLE
Not working in android

### ISSUE THREAD

**Issue by devesh01032008** [SsNipeR1/PythonRebooter#2]
I am Devesh Sharma from samalkha, panipat , Haryana in India. I used this program in my Andronid phone i.e realms narzo 30a it is not working in it please tell me if you can fix it 
You can visit my GitHub page using link
https://www.github.com/devesh01032008

**Comment by SsNipeR1** [comment]
> I am Devesh Sharma from samalkha, panipat , Haryana in India. I used this program in my Andronid phone i.e realms narzo 30a it is not working in it please tell me if you can fix it
> You can visit my GitHub page using link
> https://www.github.com/devesh01032008

Do you have root access?

**Comment by devesh01032008** [comment]
Not yet

**Comment by devesh01032008** [comment]
Would you work with me in my repository. I am in class 9 and know python very well. I am creating a repository for various python program to solve common uses for practicing python. Where do you live and can you tell me your real name my resume name is Devesh and I live in Panipat Haryana located in India

**Comment by devesh01032008** [comment]
Not respond
